334K available
Compiling funcions\FUNCSPRO.PRG
funcions\FUNCSPRO.PRG(2430)    Warning C1004  Ambiguous reference, assuming memvar: 'CSAVPAN'
funcions\FUNCSPRO.PRG(2440)    Warning C1004  Ambiguous reference, assuming memvar: 'NAVANCE'
funcions\FUNCSPRO.PRG(2442)    Warning C1003  Ambiguous reference: 'NAVANCE'
funcions\FUNCSPRO.PRG(2444)    Warning C1003  Ambiguous reference: 'NAVANCE'
funcions\FUNCSPRO.PRG(2469)    Warning C1003  Ambiguous reference: 'CSAVPAN'
funcions\FUNCSPRO.PRG(2548)    Warning C1004  Ambiguous reference, assuming memvar: 'LHAYERR'
funcions\FUNCSPRO.PRG(2557)    Warning C1004  Ambiguous reference, assuming memvar: 'LHAYERR'
funcions\FUNCSPRO.PRG(2560)    Warning C1003  Ambiguous reference: 'LHAYERR'
funcions\FUNCSPRO.PRG(2704)    Warning C1004  Ambiguous reference, assuming memvar: 'NTOTAL'
funcions\FUNCSPRO.PRG(2705)    Warning C1004  Ambiguous reference, assuming memvar: 'I'
funcions\FUNCSPRO.PRG(2705)    Warning C1004  Ambiguous reference, assuming memvar: 'I'
funcions\FUNCSPRO.PRG(2705)    Warning C1004  Ambiguous reference, assuming memvar: 'I'
funcions\FUNCSPRO.PRG(2705)    Warning C1003  Ambiguous reference: 'I'
funcions\FUNCSPRO.PRG(2705)    Warning C1003  Ambiguous reference: 'NTOTAL'
funcions\FUNCSPRO.PRG(2707)    Warning C1003  Ambiguous reference: 'I'
funcions\FUNCSPRO.PRG(2707)    Warning C1004  Ambiguous reference, assuming memvar: 'CINTENS'
funcions\FUNCSPRO.PRG(2710)    Warning C1003  Ambiguous reference: 'CINTENS'
funcions\FUNCSPRO.PRG(2710)    Warning C1003  Ambiguous reference: 'I'
funcions\FUNCSPRO.PRG(2710)    Warning C1003  Ambiguous reference: 'NTOTAL'
19 warnings                
Code size 33450, Symbols 7040, Constants 10982
