<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">

 <Styles>
  <Style ss:ID="s21">
   <Font x:Family="Swiss" ss:Bold="1"/>
  </Style>
 </Styles>
 <Worksheet ss:Name="MATERIAS">
  <Table ss:ExpandedColumnCount="2" ss:ExpandedRowCount="3" x:FullColumns="1"
   x:FullRows="1" ss:DefaultColumnWidth="60">
   <Row>
    <Cell ss:StyleID="s21"><Data ss:Type="String">CODIGO</Data></Cell>
    <Cell ss:StyleID="s21"><Data ss:Type="String">MATERIA</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="Number">121</Data></Cell>
    <Cell><Data ss:Type="String">FISICIA</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">121 is 11*11</Data></Cell>
    <Cell><Data ss:Type="String">QUIMICA</Data></Cell>
   </Row>
  </Table>
 </Worksheet>
</Workbook>
