	  MODIFICACIONES PENDIENTES PARA EL SISTEMA DE CONTABILIDAD.


NOV /97

- Fecha de Entrega: Nov 01/97
  Fecha de Inicio :                    Fecha Final:
  Programa para   : Resumen de Indicadores
  Colegios........: La Merced.

- Fecha de Entrega: Nov 30/97
  Fecha de Inicio :                    Fecha Final:
  Programa para   : Adecuaci¢n nivel 12 de Bto para el Nocturno
  Colegios........: Tecnol¢gico.


FEB /98

- Fecha de Entrega: Feb 01/98
  Fecha de Inicio :                    Fecha Final:
  Programa para   : Adecuaci¢n Parte t‚cnica.
  Colegios........: Tecnol¢gico.

- Fecha de Entrega: Feb 01/98
  Fecha de Inicio :                    Fecha Final:
  Programa para   : Adecuaci¢n de logros
  Colegios........: La Salle

- Fecha de Entrega: Feb 01/98
  Fecha de Inicio :                    Fecha Final:
  Programa para   : Certificados
  Colegios........: La Salle