<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<w:wordDocument
   xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml"
   xmlns:wx="http://schemas.microsoft.com/office/word/2003/auxHint"
   xmlns:o="urn:schemas-microsoft-com:office:office"
   w:macrosPresent="no"
   w:embeddedObjPresent="no"
   w:ocxPresent="no"
   xml:space="preserve">

  <w:body>
      <w:p>
          <w:r>
          <w:t>This is the first paragraph</w:t>
          </w:r>
      </w:p>

        <w:p>
          <w:r>
            <w:t>This is a heading</w:t>
          </w:r>
        </w:p>

  </w:body>
</w:wordDocument>
