/*                   SISTEMA DE CONTABILIDAD ACADEMICA
		   REGISTRO DE MODIFICACIONES PENDIENTES

*------------------------------------------------------------------------*
*                  PROCESOS PENDIENTES DE PROGRAMANCION                  *
*------------------------------------------------------------------------*/
Codigo No. 2002ENE-1
Fecha y Hora..: Inicio:         Final:         Versi¢n:
Titulo........: Los Logros e Indicadores
Tipo..........: Modificaci¢n Sustancial

Descripci¢n:
- Clasificar los Juicios en Logros e Indicacores de Logros

*========================================================================*
Codigo No. 2002ENE-2
Fecha y Hora..: Inicio:         Final:         Versi¢n:
Titulo........: Duplicaci¢n de C¢digos
Tipo..........: Mejora al Sistema. Soporte

Descripci¢n:
- Utilidad para detectar c¢digos repetidos.

*========================================================================*
Codigo No. 2002ENE-3
Fecha y Hora..: Inicio:         Final:         Versi¢n:
Titulo........: Seguimiento del Estudiante
Tipo..........: Mejora Sustancial al Sistema.

Descripci¢n:
- Permitir grabar por parte de los profesores el seguimiento de los
  estudiantes.

*========================================================================*
Codigo No. 2002ENE-4
Fecha y Hora..: Inicio:         Final:         Versi¢n:
Titulo........: Control de los Indicadores Por Recuperar o Recuperados
Tipo..........: Mejora Sustancial al Sistema.

Descripci¢n:
- El profesor debe digitar el control de los indicadores
- Imprimir planilla de Control
- Modificar el Boletin
- Imprimir informe de Recuperaciones.

*========================================================================*
Codigo No. 2002ENE-5
Fecha y Hora..: Inicio:         Final:         Versi¢n:
Titulo........: Listas de Clase con Titulares
Tipo..........: Adici¢n

Descripci¢n:
- Imprimir listas con los nombres de titulares.
